version: '3.7'

networks:
    qmediator:
        driver: bridge

services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        hostname: rabbitmq
        container_name: rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: rabbitmq
            RABBITMQ_DEFAULT_PASS: rabbitmq
            RABBITMQ_DEFAULT_VHOST: /
        ports:
            - 15672:15672
            - 5672:5672
        labels:
            NAME: rabbitmq
        networks:
          - qmediator

    qmediator_consumer:
        hostname: qmediator_consumer
        container_name: qmediator_consumer
        restart: always
        build:
            context: ".."
            dockerfile: config/Dockerfile
        environment:
            RABBITMQ_HOST: rabbitmq
        depends_on:
            - rabbitmq
        networks:
            - qmediator


