version: '3.3'

networks:
    qmediator:
        driver: bridge

services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        hostname: ${RABBITMQ_HOST}
        container_name: ${RABBITMQ_HOST}
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
            RABBITMQ_DEFAULT_VHOST: /
        ports:
            - 15672:15672
            - 5672:5672
        labels:
            NAME: rabbitmq
        networks:
          - qmediator

    qmediator_consumer:
        hostname: ${QMEDIATOR_CONSUMER_HOST}
        container_name: ${QMEDIATOR_CONSUMER_HOST}
        restart: always
        build:
            context: ".."
            dockerfile: config/Dockerfile
        environment:
            RABBITMQ_HOST: ${RABBITMQ_HOST}
            DOBIE_HOST: ${DOBIE_HOST}
        depends_on:
            - rabbitmq
        networks:
            - qmediator


